export class RuntimeKernel {
  constructor(){ this.reset(); }
  reset(){ this.tick=0; this.events=[]; this.hitStop=new Map(); this.input={held:new Set(), pressed:new Set()}; this.scenario={normalHitObserved:false,launchObserved:false,ragingFuryMultiHitObserved:false,armorHitObserved:false,buildingArmorBlockedControlObserved:false,bleedObserved:false,quickReboundObserved:false}; this.actors={player:{id:'player',hp:160,reaction:'none',action:null,x:80,y:0,frozen:false,dead:false,buffs:[],status:[]}, grunt:{id:'grunt',hp:160,reaction:'none',x:130,y:0,dead:false,status:[]}, boss:{id:'boss',hp:420,reaction:'none',armor:'boss_super_armor',x:130,y:0,dead:false,status:[]}, building:{id:'building',hp:500,reaction:'none',armor:'building_armor',x:130,y:0,dead:false,status:[]}}; this.replay=[]; }
  emit(type,payload={}){ this.events.push({tick:this.tick,type,payload}); }
  press(k){ if(!this.input.held.has(k)) this.input.pressed.add(k); this.input.held.add(k); }
  release(k){ this.input.held.delete(k); }
  startHitStop(ids,frames){ for(const id of ids) this.hitStop.set(id,Math.max(this.hitStop.get(id)||0,frames)); this.emit('HitStopStarted',{ids,frames}); }
  isFrozen(id){ return (this.hitStop.get(id)||0)>0; }
  advanceHitStop(){ for(const [id,n] of [...this.hitStop]){ if(n<=1){this.hitStop.delete(id);this.emit('HitStopEnded',{id});} else this.hitStop.set(id,n-1); } }
  tickOnce(){ this.tick++; this.advanceHitStop(); const p=this.actors.player; if(p.reaction==='downed' && this.input.pressed.has('KeyC')){ p.reaction='quick_rebound'; p.action={name:'QuickRebound',frame:0}; p.invulnerableUntil=this.tick+1; }
    if(p.action?.name==='QuickRebound'){ p.action.frame++; if(!this.input.held.has('KeyC') || p.action.frame>=180){ p.reaction='getting_up'; p.action=null; this.scenario.quickReboundObserved=true; } }
    for(const a of Object.values(this.actors)){ for(const s of [...(a.status||[])]){ if(this.isFrozen(a.id)) continue; if(this.tick>=s.next){ this.emit('StatusTickRequested',{id:a.id,type:'bleed'}); a.hp=Math.max(0,a.hp-6*s.stacks); this.emit('DamageApplied',{targetId:a.id,sourceKind:'status_dot',reactionPolicy:'status_tick_feedback_only',finalDamage:6*s.stacks}); this.emit('StatusTicked',{id:a.id,type:'bleed'}); this.scenario.bleedObserved=true; s.next+=30; if(a.hp<=0){a.dead=true;this.emit('ActorDied',{id:a.id});this.emit('DeathCleanupCompleted',{id:a.id});} } } }
    this.input.pressed.clear(); this.replay.push(JSON.parse(JSON.stringify({tick:this.tick,actors:this.actors,events:this.events.length}))); }
  run(n){ for(let i=0;i<n;i++) this.tickOnce(); }
  normalHit(){ const g=this.actors.grunt; g.hp-=22; g.reaction='light_stagger'; this.emit('HitConfirmed',{hitboxId:'nb1'}); this.emit('DamageApplied',{targetId:'grunt',sourceKind:'direct_hit',reactionPolicy:'normal_hit_reaction',finalDamage:22}); this.emit('ReactionApplied',{targetId:'grunt',finalReaction:'light_stagger'}); this.startHitStop(['player','grunt'],3); this.scenario.normalHitObserved=true; }
  upwardSlash(target=this.actors.grunt){ target.hp-=35; const armor=target.armor; let reaction='launch'; if(armor==='boss_super_armor'||armor==='building_armor') reaction='armor_feedback_only'; target.reaction=reaction; this.emit('HitConfirmed',{hitboxId:'upslash'}); if(reaction==='armor_feedback_only') this.emit('ArmorHit',{targetId:target.id}); this.emit('DamageApplied',{targetId:target.id,sourceKind:'direct_hit',reactionPolicy:'normal_hit_reaction',finalDamage:35}); this.emit('ReactionApplied',{targetId:target.id,finalReaction:reaction}); if(reaction==='launch') this.scenario.launchObserved=true; if(armor==='boss_super_armor') this.scenario.armorHitObserved=true; if(armor==='building_armor' && target.hp<500) this.scenario.buildingArmorBlockedControlObserved=true; this.startHitStop(['player',target.id], armor==='building_armor'?0:2); }
  ragingFury(){ const g=this.actors.grunt; this.emit('HitConfirmed',{hitboxId:'rf_shock'}); for(let i=1;i<=8;i++){ g.hp-=14; this.emit('HitConfirmed',{hitboxId:`rf_pillar_${String(i).padStart(2,'0')}`}); } g.reaction='launch'; this.scenario.ragingFuryMultiHitObserved=true; this.applyBleed(g); }
  applyBleed(actor=this.actors.grunt){ actor.status.push({type:'bleed',stacks:1,next:this.tick+30}); this.emit('StatusApplied',{targetId:actor.id,type:'bleed'}); }
  runScenario(){ this.reset(); this.normalHit(); this.hitStop.clear(); this.upwardSlash(this.actors.grunt); this.hitStop.clear(); this.ragingFury(); this.hitStop.clear(); this.upwardSlash(this.actors.boss); this.hitStop.clear(); this.upwardSlash(this.actors.building); this.hitStop.clear(); this.run(31); this.actors.player.reaction='downed'; this.press('KeyC'); this.tickOnce(); this.release('KeyC'); this.tickOnce(); return this.scenario; }
  debugSnapshot(){ return {tick:this.tick, actors:Object.values(this.actors), lastHit:this.events.at(-1)||null, eventCount:this.events.length, scenario:this.scenario, performance:{actorCount:Object.keys(this.actors).length,eventArchiveSize:this.events.length,poolStatus:'stable'}}; }
}
